### ISSUE TITLE
How many views do you select during testing?

### ISSUE THREAD

**Issue by lqzhao** [maxjaritz/mvpnet#1]
Dear Mr Jaritz,
Thanks for your excellent work! After reading your paper and running the code you provided, I have one question.
How many views do you select when you train and test MVPNet, respectively?
Is 67.92 achieved in ResNet34 + PointNet++(more centroids) + 5 views configuration?
![image](https://user-images.githubusercontent.com/43566465/74550407-4a5f5980-4f8c-11ea-9e66-dd45ee01b59d.png)

**Comment by maxjaritz** [comment]
Hi,
for the score that we report in the README.md, we use 3 views for training and 5 views for testing.

For training it is specified in the following line in the config file:
```
num_rgbd_frames: 3
```

For testing, we can override this parameter as follows:
```
python mvpnet/test_mvpnet_3d.py --cfg configs/scannet/mvpnet_3d_unet_resnet34_pn2ssg.yaml  --num-views 5
```

**Comment by lqzhao** [comment]
Ok, got it. I find that mIoU could reach 0.88 for training but only 0.68 for testing. Something limits the performance for testing. Are there too many points in a whole scene so that 5 views cannot match 90% of them? Or for other reasons?

**Comment by maxjaritz** [comment]
This is normal, as the network overfits to some extent to the training set.
