### ISSUE TITLE
alternate dataset

### ISSUE THREAD

**Issue by abhigoku10** [maxjaritz/mvpnet#2]
@Jiayuan-Gu @maxjaritz thanks for open sourcing the wonderfull work , i had few queries
Q1 have you trained the architecture on the available other dataset like semanttic Kitti and 3D dataset
Q2 If not trained can we follow the same training pipeline , if trained can you please share the pre-trained model
Q3 can we use the currently pre-trained model to test on custom dataset which less number of point cloud density

Thanks in advance

**Comment by maxjaritz** [comment]
Hi,
Q1+Q2: We have tested on S3DIS, but this is currently not supported in the published code. However, it should be rather straightforward to extend our code, as S3DIS is a similar multi-view indoor dataset like ScanNet. MVPNet is tailored to aggregating those multiple views into the global point cloud. Differently from those multi-view indoor datasets, SemanticKITTI is outdoor and only single view, i.e. the point cloud is obtained from a single LiDAR scan that is synchronized with the camera. In addition, the field of view of the LiDAR is 360 deg around the vehicle, while the camera is just front view. You could design a single view version of MVPNet only using the 3D points that project into the front view camera OR aggregate multiple timesteps into a global point cloud using the IMU data.

Q3: Yes.

**Comment by abhigoku10** [comment]
@maxjaritz  thanks for the quick response . can you please elaborate on "**you could design a single view version of MVPNet only using the 3D points that project into the front view camera OR aggregate multiple timesteps into a global point cloud using the IMU data.** " and how i can modify the code to get it working for semanttic kitti

**Comment by maxjaritz** [comment]
Hi,
For a single view version, you could remove the aggregation module and set the number of views to 1.
For SemanticKITTI, you would also need to preprocess, i.e. sample the 3D points in the field of view of the camera image. Of course, you would also need to write the dataloader.
